loki:
  serviceName: logging
nameOverride: logging

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceMonitor:
  enabled: true
  namespace: monitoring
  namespaceSelector:
    matchNames:
      - logging

config:
  clients:
    - url: http://logging:3100/loki/api/v1/push