namespaceOverride: monitoring

defaultRules:
  create: false

alertmanager:
  enabled: false
grafana:
  enabled: true
  namespaceOverride: monitoring
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://logging.logging.svc.cluster.local:3100
      jsonData:
        maxLines: 1000