apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
commonLabels:
  app.kubernetes.io/name: kuard
resources:
  - ./deployment.yaml
  - ./namespace.yaml
  - ./service.yaml
  - ./hpa.yaml
images:
  - name: kuard
    newName: gcr.io/kuar-demo/kuard-amd64
    newTag: blue